### ISSUE TITLE
Update Error from 1.1.3 to latest

### ISSUE THREAD

**Issue by bf3883** [ActiveByte/homebridge-loxone-connect#13]
Update stops with this lines

1530 info run lxcommunicator@1.1.1 postinstall node_modules/homebridge-loxone-connect/node_modules/lxcommunicator node ./browserify.js
1531 info run lxcommunicator@1.1.1 postinstall { code: 0, signal: null }
1532 timing build:run:postinstall:node_modules/homebridge-loxone-connect/node_modules/lxcommunicator Completed in 205331ms
1533 timing build:run:postinstall Completed in 205331ms
1534 timing build:deps Completed in 216208ms
1535 timing build Completed in 216212ms
1536 timing reify:build Completed in 216222ms
1537 timing reify:rollback:createSparse Completed in 7527ms
1538 timing reify:rollback:retireShallow Completed in 5ms
1539 timing command:install Completed in 333480ms
1540 verbose stack Error: process terminated
1540 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:194:39
1540 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
1540 verbose stack     at process.emit (node:events:402:35)
1541 verbose cwd /homebridge
1542 verbose Linux 4.19.118-v7+
1543 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "homebridge-loxone-connect@latest"
1544 verbose node v16.13.0
1545 verbose npm  v8.1.0
1546 error process terminated
1547 error signal SIGTERM
1548 verbose exit 1

**Comment by ActiveByte** [comment]
Hey @bf3883 , maybe you can try to completely remove the plugin and install it again?
Or if possible try it on a clean install, since i did not get any other reports of this i think it could be on your side.

Please let me know

**Comment by bf3883** [comment]
Same error on clean fresh hombridge installation.
homebridge is running on a raspberry with docker installation

**Comment by ActiveByte** [comment]
What docker container are you using?
I have the same setup
