### ISSUE TITLE
Plugin crashing with "DefaultMood"

### ISSUE THREAD

**Issue by jo-math** [ActiveByte/homebridge-loxone-connect#32]
`Hi,`

I really would love to have the Loxone stuff in Apples HomeKit. 
I created a loxone user special for home bridge.
I granted the user privilege and the privilege for the living room.
During startup, the plugin crashes with the following error

```
Jan 28 20:39:15 ds9-control homebridge[4343]: [28/01/2023, 20:39:15] [Config] Initializing config platform...
Jan 28 20:39:15 ds9-control homebridge[4343]: [28/01/2023, 20:39:15] [Config] Spawning homebridge-config-ui-x with PID 4447
Jan 28 20:39:15 ds9-control homebridge[4343]: [28/01/2023, 20:39:15] [LoxoneWs] Initializing LoxoneWs platform...
Jan 28 20:39:15 ds9-control homebridge[4343]: [28/01/2023, 20:39:15] [LoxoneWs] Trying to connect to Miniserver
Jan 28 20:39:17 ds9-control homebridge[4343]: [28/01/2023, 20:39:17] [LoxoneWs] Connected
Jan 28 20:39:17 ds9-control homebridge[4343]: [28/01/2023, 20:39:17] TypeError: Cannot read properties of undefined (reading 'DefaultMood')
Jan 28 20:39:17 ds9-control homebridge[4343]:     at Object.moduleexports.Factory.traverseSitemap (/usr/lib/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:333:75)
Jan 28 20:39:17 ds9-control homebridge[4343]:     at moduleexports.Factory.parseSitemap (/usr/lib/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:46:37)
Jan 28 20:39:17 ds9-control homebridge[4343]:     at LoxPlatform.accessories (/usr/lib/node_modules/homebridge-loxone-connect/index.js:133:26)
Jan 28 20:39:17 ds9-control homebridge[4343]: [28/01/2023, 20:39:17] Got SIGTERM, shutting down Homebridge...
Jan 28 20:39:18 ds9-control homebridge[4343]: [28/01/2023, 20:39:18] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
Jan 28 20:39:18 ds9-control homebridge[4343]:     at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
Jan 28 20:39:18 ds9-control homebridge[4343]:     at Server.setServerStatus (/usr/lib/node_modules/homebridge/src/server.ts:155:45)
Jan 28 20:39:18 ds9-control homebridge[4343]:     at Server.teardown (/usr/lib/node_modules/homebridge/src/server.ts:199:10)
Jan 28 20:39:18 ds9-control homebridge[4343]:     at signalHandler (/usr/lib/node_modules/homebridge/src/cli.ts:93:12)
Jan 28 20:39:18 ds9-control homebridge[4343]:     at process.emit (node:events:513:28)
Jan 28 20:39:18 ds9-control homebridge[4343]:     at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
Jan 28 20:39:18 ds9-control homebridge[4343]: Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
```

**Comment by bert-willekens** [comment]
Do you have DefaultMood in your alias configuration?

````
{
    "platform": "LoxoneWs",
     ...
    "options": {
        .....
    },
    "alias": {
        .....
        "Lock": "Lock",
        "DefaultMood": "Off"
    }
}
````

**Comment by jo-math** [comment]
Thanks for your hint, now I get

```
Jan 31 20:41:07 ds9-control homebridge[31150]: [31/01/2023, 20:41:07] Loading 2 platforms...
Jan 31 20:41:07 ds9-control homebridge[31150]: [31/01/2023, 20:41:07] [Config] Initializing config platform...
Jan 31 20:41:07 ds9-control homebridge[31150]: [31/01/2023, 20:41:07] [Config] Spawning homebridge-config-ui-x with PID 31186
Jan 31 20:41:07 ds9-control homebridge[31150]: [31/01/2023, 20:41:07] [LoxoneWs] Initializing LoxoneWs platform...
Jan 31 20:41:07 ds9-control homebridge[31150]: [31/01/2023, 20:41:07] [LoxoneWs] Trying to connect to Miniserver
Jan 31 20:41:09 ds9-control homebridge[31150]: [31/01/2023, 20:41:09] [LoxoneWs] Connected
Jan 31 20:41:09 ds9-control homebridge[31150]: [31/01/2023, 20:41:09] SyntaxError: Unexpected token u in JSON at position 0
Jan 31 20:41:09 ds9-control homebridge[31150]:     at JSON.parse (<anonymous>)
Jan 31 20:41:09 ds9-control homebridge[31150]:     at Object.moduleexports.Factory.traverseSitemap (/usr/lib/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:331:48)
Jan 31 20:41:09 ds9-control homebridge[31150]:     at moduleexports.Factory.parseSitemap (/usr/lib/node_modules/homebridge-loxone-connect/libs/ItemFactory.js:46:37)
Jan 31 20:41:09 ds9-control homebridge[31150]:     at LoxPlatform.accessories (/usr/lib/node_modules/homebridge-loxone-connect/index.js:133:26)
Jan 31 20:41:09 ds9-control homebridge[31150]: [31/01/2023, 20:41:09] Got SIGTERM, shutting down Homebridge...

```
