### ISSUE TITLE
Homebridge crashes after a few seconds

### ISSUE THREAD

**Issue by rc-itcon** [ActiveByte/homebridge-loxone-connect#7]
Hello,

when i saw in the loxforum that there is a new homebridge plugin i tried it immediatly but got the following situation:
I think the plugin can connect correctly because for a short time of period i saw the two test devices in homebridge and also in home app, but then it crashes.

logs:

[28/10/2021, 20:59:42] [[39mRegistering platform 'homebridge-config-ui-x.config'
[28/10/2021, 20:59:43] ^[[39mLoaded plugin: homebridge-loxone-connect@1.1.3
homebridge API version: 2.7
[28/10/2021, 20:59:43] [[39mRegistering platform 'homebridge-loxone-connect.LoxoneWs'
[28/10/2021, 20:59:43] [[39mLoading 2 platforms...
[28/10/2021, 20:59:43] [[39m^[[36m[Config]^[[39m Initializing config platform...
[28/10/2021, 20:59:43] [[39m^[[36m[Config]^[[39m Running in Service Mode
[28/10/2021, 20:59:43] [[39m^[[36m[LoxoneWs]^[[39m Initializing LoxoneWs platform...
[28/10/2021, 20:59:43] [[39m^[[36m[LoxoneWs]^[[39m Getting Loxone configuration.
[28/10/2021, 20:59:43] [[39m^[[36m[LoxoneWs]^[[39m Platform - Waiting 8 seconds until initial state is retrieved via WebSocket.
[28/10/2021, 20:59:43] [[39m^[[36m[LoxoneWs]^[[39m WS: connect
Websocket Connection closed:  1000 normally closed
[[37m[28/10/2021, 20:59:45] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connect
Websocket Connection closed:  1000 normally closed
[28/10/2021, 20:59:47] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connect
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - Retrieving initial config from http://10.0.0.120:80/data/LoxApp3.json
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Licht Arbeitszimmer' of type LightControllerV2 is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - Accessory Found: Deckenlampe of Licht Arbeitszimmer
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - Accessory Found: Rolladen
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Luftfeuchte' of type InfoOnlyAnalog is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Heizung-Kühlung' of type IRoomControllerV2 is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Heating and Cooling of Heizung-Kühlung' of type IRCV2Daytimer is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Stellantrieb Tree' of type InfoOnlyAnalog is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Temperatur' of type InfoOnlyAnalog is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Wecker' of type AlarmClock is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'geschlossen' of type InfoOnlyDigital is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - The widget 'Internetverbindung' of type InfoOnlyDigital is an item not handled.
[28/10/2021, 20:59:51] ^[[39m^[[36m[LoxoneWs]^[[39m Platform - Total accessory count 2 across 0 rooms.
[28/10/2021, 20:59:51] ^[[39mInitializing platform accessory 'Deckenlampe of Licht Arbeitszimmer'...
[28/10/2021, 20:59:51] ^[[39mInitializing platform accessory 'Rolladen'...
Preparing Advertiser for 'Homebridge 32CD FF76' using bonjour-hap backend!

**But then it starts to loop and crash.**

[28/10/2021, 21:00:14] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connection error, reconnecting...Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Websocket Connection closed:  1006 Socket Error: undefined ERR_STREAM_WRITE_AFTER_END
[28/10/2021, 21:00:16] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connect
WebSocket error:  Socket Error: undefined ERR_STREAM_WRITE_AFTER_END 1006
[28/10/2021, 21:00:16] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connection error, reconnecting...Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Websocket Connection closed:  1006 Socket Error: undefined ERR_STREAM_WRITE_AFTER_END
[28/10/2021, 21:00:16] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connect
WebSocket error:  Socket Error: undefined ERR_STREAM_WRITE_AFTER_END 1006
[28/10/2021, 21:00:16] ^[[39m^[[36m[LoxoneWs]^[[39m WS: connection error, reconnecting...Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Websocket Connection closed:  1006 Socket Error: undefined ERR_STREAM_WRITE_AFTER_END
[28/10/2021, 21:00:18] ^[[39m^[[31mTypeError: Cannot read property 'closeDescription' of undefined^[[39m
    at Connection.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-connect/node_modules/node-lox-ws-api/lib/Connection.js:62:62)^[[39m
    at WebSocketClient.emit (events.js:400:28)^[[39m
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-loxone-connect/node_modules/websocket/lib/WebSocketClient.js:339:10)^[[39m
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-connect/node_modules/websocket/lib/WebSocketClient.js:278:18)^[[39m
    at ClientRequest.emit (events.js:400:28)^[[39m
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)^[[39m
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)^[[39m
    at Socket.socketOnData (_http_client.js:515:22)^[[39m
    at Socket.emit (events.js:400:28)^[[39m
    at addChunk (internal/streams/readable.js:293:12)^[[39m
[28/10/2021, 21:00:18] ^[[39mGot SIGTERM, shutting down Homebridge...
[28/10/2021, 21:00:23]^[[0m ^[[36m[HB Supervisor]^[[0m Homebridge Process Ended. Code: 143, Signal: null

**After auto-restart the looping starts directly and loxone is blocking the IP.**

Websocket Connection closed:  4003 Forbidden - IP 10.0.0.124 temporarily blocked, too many failed login attempts (31)

Has anyone an idea what the Problem could be?

thanks a lot
regards
Christian

**Comment by digimon-Denmark** [comment]
Same issue I have. I have try new IP . New username and password nothing works.. it’s broke

**Comment by imbrechtsjurgen** [comment]
I'm having the same issue.
running loxone firmware 12.2.10.27

**Comment by ActiveByte** [comment]
Can you test if the problem still occurs with the latest version of this plugin?

**Comment by rc-itcon** [comment]
until know it works perfectly with the new Version. 

lights and shades are tested.

Thank you very much I appreciate it.

**Comment by ActiveByte** [comment]
Glad to hear that!
